# Generated by Django 4.1.7 on 2023-03-18 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('citasMed', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='horariosmedicos',
            name='medico',
        ),
    ]
