# Generated by Django 4.0.5 on 2022-07-18 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citasMed', '0002_horariosmedicos_alter_citasmedicas_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='horariosmedicos',
            name='fechaCita',
            field=models.DateField(blank=True, db_column='FechaCita', null=True),
        ),
        migrations.AlterField(
            model_name='horariosmedicos',
            name='hora_fin',
            field=models.TimeField(max_length=10),
        ),
        migrations.AlterField(
            model_name='horariosmedicos',
            name='hora_inicio',
            field=models.TimeField(max_length=10),
        ),
    ]
