# Generated by Django 4.1.7 on 2023-03-19 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citasMed', '0002_remove_horariosmedicos_medico'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='citasmedicas',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='citasmedicas',
            name='hora',
        ),
        migrations.AddField(
            model_name='citasmedicas',
            name='fecha_hora',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
