# Generated by Django 4.0.5 on 2022-07-21 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citasMed', '0003_horariosmedicos_fechacita_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='horariosmedicos',
            name='fechaCita',
        ),
        migrations.AddField(
            model_name='citasmedicas',
            name='fechaCita',
            field=models.DateField(blank=True, db_column='FechaCita', null=True),
        ),
    ]
