# Generated by Django 4.1.7 on 2023-02-23 15:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_countries.fields
import usuarioLogin.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('celular', models.CharField(blank=True, db_column='Celular', max_length=50, null=True)),
                ('direccion', models.TextField(blank=True, db_column='Direccion', null=True)),
                ('Fecha_Nacimiento', models.DateField(blank=True, db_column='Fecha_Nacimiento', null=True)),
                ('identificacion', models.CharField(db_column='Identificacion', max_length=50, null=True, validators=[usuarioLogin.models.validate_unique_and_numeric])),
                ('tipo_identificacion', models.CharField(blank=True, choices=[('CC', 'Cedula de Ciudadania'), ('PS', 'Pasaporte')], db_column='Tipo de identificacion', max_length=2, null=True)),
                ('paisOrigen', django_countries.fields.CountryField(max_length=2)),
                ('genero', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino')], db_column='Genero', max_length=1, null=True)),
                ('user', models.OneToOneField(blank=True, db_column='usuario', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Personas',
                'db_table': 'persona',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_registrodesde', models.DateField(blank=True, db_column='registrodesde', default=django.utils.timezone.now, null=True)),
                ('Persona', models.OneToOneField(blank=True, db_column='Persona', null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarioLogin.persona')),
                ('user', models.OneToOneField(blank=True, db_column='Usuario', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Pacientes',
                'db_table': 'paciente',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_colegiado', models.IntegerField(blank=True, db_column='Numero_colegiado', null=True)),
                ('m_registrodesde', models.DateField(blank=True, db_column='M_registrodesde', default=django.utils.timezone.now, null=True)),
                ('estado', models.CharField(blank=True, choices=[('DI', 'Disponible'), ('OC', 'Ocupado')], db_column='Estado_m', max_length=10, null=True)),
                ('Persona', models.OneToOneField(blank=True, db_column='Persona', null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarioLogin.persona')),
                ('user', models.OneToOneField(blank=True, db_column='Usuario', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Médicos',
                'db_table': 'medico',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Historialclinico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechacreacion', models.DateField(blank=True, db_column='Fechacreacion', null=True)),
                ('ultimamodificacion', models.DateField(blank=True, db_column='Ultimamodificacion', null=True)),
                ('paciente', models.OneToOneField(blank=True, db_column='Paciente', null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarioLogin.paciente')),
            ],
            options={
                'verbose_name_plural': 'Historiales clinicos',
                'db_table': 'historialclinico',
                'managed': True,
            },
        ),
    ]
