# Generated by Django 4.0.5 on 2022-07-04 23:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Historialclinico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechacreacion', models.DateField(blank=True, db_column='Fechacreacion', null=True)),
                ('ultimamodificacion', models.DateField(blank=True, db_column='Ultimamodificacion', null=True)),
            ],
            options={
                'db_table': 'historialclinico',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_registrodesde', models.DateField(blank=True, db_column='P_registrodesde', null=True)),
                ('historial_clinico', models.OneToOneField(blank=True, db_column='Historial_Clinico', null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarioLogin.historialclinico')),
            ],
            options={
                'db_table': 'paciente',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apellidos', models.CharField(blank=True, db_column='Apellidos', max_length=50, null=True)),
                ('nombres', models.CharField(blank=True, db_column='Nombres', max_length=50, null=True)),
                ('celular', models.CharField(blank=True, db_column='Celular', max_length=50, null=True)),
                ('correo', models.CharField(blank=True, db_column='Correo', max_length=50, null=True)),
                ('direccion', models.TextField(blank=True, db_column='Direccion', null=True)),
                ('fecha_nacimiento', models.DateField(blank=True, db_column='Fecha_Nacimiento', null=True)),
                ('identificacion', models.CharField(blank=True, db_column='Identificacion', max_length=50, null=True)),
                ('tipo_identificacion', models.CharField(blank=True, db_column='Tipo de identificacion', max_length=50, null=True)),
                ('paisOrigen', django_countries.fields.CountryField(max_length=2)),
                ('genero', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino')], db_column='Genero', max_length=1, null=True)),
                ('paciente', models.OneToOneField(blank=True, db_column='Paciente', null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarioLogin.paciente')),
                ('user', models.OneToOneField(blank=True, db_column='usuario', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'persona',
                'managed': True,
            },
        ),
    ]
