# Generated by Django 4.1.7 on 2023-03-17 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citasMed', '0001_initial'),
        ('usuarioLogin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historialclinico',
            name='enfermedades',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='medico',
            name='especialidad',
            field=models.ManyToManyField(blank=True, to='citasMed.especialidadmedica'),
        ),
    ]
