# Generated by Django 4.0.5 on 2022-07-14 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarioLogin', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medico',
            name='especialidadF',
        ),
        migrations.RemoveField(
            model_name='persona',
            name='apellidos',
        ),
        migrations.RemoveField(
            model_name='persona',
            name='correo',
        ),
        migrations.RemoveField(
            model_name='persona',
            name='nombres',
        ),
        migrations.AlterField(
            model_name='persona',
            name='tipo_identificacion',
            field=models.CharField(blank=True, choices=[('CC', 'Cedula de Ciudadania'), ('PS', 'Pasaporte')], db_column='Tipo de identificacion', max_length=2, null=True),
        ),
    ]
