# Generated by Django 4.0.5 on 2022-07-25 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('citasMed', '0004_remove_horariosmedicos_fechacita_and_more'),
        ('usuarioLogin', '0002_remove_medico_especialidadf_remove_persona_apellidos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medico',
            name='especialidadMedica',
            field=models.ForeignKey(blank=True, db_column='Especialidad_medica', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Especialidad_Medica', to='citasMed.especialidadmedica'),
        ),
    ]
