# Generated by Django 4.1.7 on 2023-03-17 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarioLogin', '0002_historialclinico_enfermedades_medico_especialidad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historialclinico',
            name='enfermedades',
        ),
    ]
