# Generated by Django 4.1.7 on 2023-03-17 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarioLogin', '0003_remove_historialclinico_enfermedades'),
    ]

    operations = [
    ]
