# Generated by Django 4.1 on 2023-01-05 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarioLogin', '0003_medico_especialidadmedica'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medico',
            options={'managed': True, 'verbose_name_plural': 'Médicos'},
        ),
        migrations.AlterModelTable(
            name='medico',
            table='medico',
        ),
    ]
