# Generated by Django 4.1.7 on 2023-03-18 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citasMed', '0002_remove_horariosmedicos_medico'),
        ('usuarioLogin', '0004_auto_20230316_2130'),
    ]

    operations = [
        migrations.AddField(
            model_name='medico',
            name='horariosmedico',
            field=models.ManyToManyField(blank=True, to='citasMed.horariosmedicos'),
        ),
    ]
