# Generated by Django 4.1 on 2023-01-07 18:19

from django.db import migrations, models
import usuarioLogin.models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarioLogin', '0005_alter_paciente_p_registrodesde'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='identificacion',
            field=models.CharField(db_column='Identificacion', max_length=50, null=True, validators=[usuarioLogin.models.validate_unique_and_numeric]),
        ),
    ]
