# Generated by Django 4.1.7 on 2023-03-18 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citasMed', '0002_remove_horariosmedicos_medico'),
        ('usuarioLogin', '0005_medico_horariosmedico'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medico',
            name='horariosmedico',
        ),
        migrations.AddField(
            model_name='medico',
            name='horariosmedicoSS',
            field=models.ManyToManyField(blank=True, to='citasMed.horariosmedicos'),
        ),
    ]
