# Generated by Django 4.1.7 on 2023-03-18 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarioLogin', '0006_remove_medico_horariosmedico_medico_horariosmedicoss'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medico',
            old_name='horariosmedicoSS',
            new_name='horariomedico',
        ),
    ]
