# Generated by Django 4.1 on 2023-01-11 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarioLogin', '0006_alter_persona_identificacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medico',
            name='especialidadMedica',
        ),
    ]
