# Generated by Django 4.1 on 2023-02-10 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarioLogin', '0008_medico_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medico',
            old_name='User',
            new_name='user',
        ),
    ]
