# Generated by Django 4.1 on 2023-02-10 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarioLogin', '0009_rename_user_medico_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medico',
            name='Persona',
        ),
    ]
