# Generated by Django 4.1 on 2023-02-11 00:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarioLogin', '0010_remove_medico_persona'),
    ]

    operations = [
        migrations.AddField(
            model_name='medico',
            name='Persona',
            field=models.OneToOneField(blank=True, db_column='Persona', null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarioLogin.persona'),
        ),
        migrations.AddField(
            model_name='medico',
            name='estado',
            field=models.CharField(blank=True, choices=[('DI', 'Disponible'), ('OC', 'Ocupado')], db_column='Estado_m', max_length=10, null=True),
        ),
    ]
